title: Chinmay Arora
email: chinmayarora2001@gmail.com
description: >-
  Chinmay Arora's blog on data science, machine learning, GenAI, and analytics engineering.
baseurl: ""
url: "https://app.chinmayarora.com"
lang: en_US
timezone: America/Chicago

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Chinmay Arora

seo:
  type: Blog
  name: Chinmay Arora Blog
  links:
    - https://www.linkedin.com/in/chinmay-arora-27682211b/
    - https://github.com/ChinmayA301

social:
  name: Chinmay Arora
  links:
    - https://www.linkedin.com/in/chinmay-arora-27682211b/
    - https://github.com/ChinmayA301
